### ISSUE TITLE
Must work with PHP 5.6

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_external_dropbox#14] opened 2017-10-12 08:23 UTC
Adjust composer.json to make sure the pulled libraries are compatible with PHP 5.

Once applied will likely require a full regression test, as this might pull older versions of some libraries which might or might not break it...

@Hemant-Mann

**Comment by DeepDiver1975** [comment] 2017-10-12 08:26
And also setup travis and run tests on all supported php versions (5.6-7.1)

**Comment by Hemant-Mann** [comment] 2017-10-12 15:28
Composer already gets the php version from the environment so if it finds that I am running 5.6 it will not download any package that requires >=7.0

**Comment by Hemant-Mann** [comment] 2017-10-12 15:30
Could you tell me how can i reproduce this bug? Because I have both PHP5.6 and PHP7.0 installed on my system
I removed PHP7.0 from the `$PATH` and then did a composer install without any change in config and it fetched library version compatible with php5.6
Repeated the same with php7 and resulted libraries were compatible with >= php7 only

**Comment by patrickjahns** [comment] 2017-10-12 15:40
@Hemant-Mann 
We do need to ship the composer dependencies pre-packaged (please download from marketplace.owncloud.com and check the tar archive).

**Comment by Hemant-Mann** [comment] 2017-10-12 15:41
Okay i got it that we have to preship them
but the preship packages will not work with php5 with current configuration

**Comment by patrickjahns** [comment] 2017-10-12 15:45
yes - we need to remove the composer.lock file and built one on php5.6 - actually did that with:

```
PHP 5.6.31 (cli) (built: Aug  7 2017 20:28:40) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

But I receive this error/problem:
```
[Thu Oct 12 17:38:47 2017] PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
[Thu Oct 12 17:38:47 2017] PHP Warning:  Cannot modify header information - headers already sent in Unknown on line 0
```

`composer.lock` that was generated https://gist.github.com/patrickjahns/5030e5a7f0c275744e7f05bce8f5a089

(not tested against 7/7.1 yet)

**Comment by patrickjahns** [comment] 2017-10-12 16:18
@neemzy

Can you test  https://github.com/owncloud/files_external_dropbox/pull/15 combined with 
 https://github.com/owncloud/core/pull/29225

When you checkout, please do a `make clean && make` in the `files_external_dropbox`

**Comment by Hemant-Mann** [comment] 2017-10-12 16:26
Hmm the composer.lock file now show `"php": ">=5.6.4"`

**Comment by patrickjahns** [comment] 2017-10-12 17:48
Not sure here - @PVince81 need to decide if it is valid to not support < 5.6.4 or if we need to.

I am working on travis right now - but I am not getting all tests green. Did all tests work for you?
Errors I am seeing:

```
1) Test\Files_external_dropbox\Dropbox::testCopy with data set #4 ('/source.txt', '/tärgét.txt')
/tärgét.txt was not created
Failed asserting that false is true.
```

**Comment by PVince81** [comment] 2017-10-13 07:20
@Hemant-Mann people who install the dropbox app do so from the marketplace, so no "composer install" is run, all libraries are already packaged. So we need to make sure that the "composer install" is run for the correct versions at **packaging time**. We can't expect whoever builds the package to always run this on a PHP 5.6 env, so best is to enforce the version in composer.json.

@patrickjahns not sure why support PHP < 5.6.4 ? What is the latest 5.6 version ?

**Comment by neemzy** [comment] 2017-10-13 07:45
@patrickjahns I've backed up my `vendor` folder, copied the `composer.json` file from the repo (same revision as your changes) and ran `composer install` myself, which should be equivalent. And it worked!!

**Comment by patrickjahns** [comment] 2017-10-13 08:08
@neemzy 
I am glad to hear that it works now! ✨ 

Just a question - did you copy `composer.json` or `composer.lock` ?

@PVince81 
The latest 5.6 is 5.6.31 July 2017
Checking http://php.net/ChangeLog-5.php#5.6.4 - 5.6.4 was released in Dec 2014

**Comment by neemzy** [comment] 2017-10-13 08:10
@patrickjahns `composer.json`

My 2 cents: noone will be mad if you don't support an outdated minor version of an outdated major version of PHP. Just make it clear in the docs ;)

**Comment by patrickjahns** [comment] 2017-10-13 08:16
@neemzy 
Do you mind trying with this `composer.lock` file? Switching `composer.json` shouldn't have made a difference

https://github.com/owncloud/files_external_dropbox/blob/af95f9883ec405a07eccfc3b00d7c3dcb0f49c97/composer.lock

**Comment by neemzy** [comment] 2017-10-13 08:20
@patrickjahns Of course it should, since I installed dependencies on my own system, which therefore took my PHP version into account. Here's the `composer.lock` that was generated: https://dpaste.neemzy.org/paste/59e07747886711875cdc3fa0#javascript

**Comment by neemzy** [comment] 2017-10-13 17:13
@patrickjahns That may be an unrelated issue, but I'm getting a lot of these:

```
PHP Fatal error:  Uncaught exception 'Doctrine\\DBAL\\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1040] Too many connections' in /path/to/owncloud/lib/private/DB/Connection.php:63\nStack trace:\n#0 /path/to/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /path/to/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /path/to/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /path/to/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /path/to/owncloud/lib/private/DB/Connection.php(146): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /path/to/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(D in /path/to/owncloud/lib/private/DB/Connection.php on line 63
```

It seems the Dropbox app is quite demanding towards my database :) If you want me to open another issue, please let me know and I will. Thanks!

**Comment by patrickjahns** [comment] 2017-10-14 08:39
@neemzy 
please open a separate issue and provide intensive information how this correlates with dropbox app

**Closed** 2017-10-19 14:30 UTC
Labels: bug, p1-urgent
