### ISSUE TITLE
Can't delete file at the first try.

### ISSUE THREAD

**Issue by cdamken** [owncloud/files_external_dropbox#31] opened 2018-02-10 20:37 UTC
I installed the 1.0.1 version.

Now I can connect without problems to Dropbox. 👍 

I tried to delete some files and the first time it says it's not possible to delete the file, the second time I try to delete,  the file can be deleted.

Log:
```
{"reqId":"IGpBsDLekyC10D1ONXxG","level":0,"time":"2018-02-10T21:27:57+01:00","remoteAddr":"10.1.10.85","user":"carlos","app":"webdav","method":"DELETE","url":"/remote.php/webdav/External-Storages/Ext-Dropbox/test1.txt","message":"Exception: {"Message":"HTTP/1.1 403 Forbidden","Exception":"Sabre\DAV\Exception\Forbidden","Code":0,"Trace":"
#0 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Tree.php(179): OCA\DAV\Connector\Sabre\File->delete()
#1 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/CorePlugin.php(287): Sabre\DAV\Tree->delete('External-Storag...')
#2 [internal function]: Sabre\DAV\CorePlugin->httpDelete(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#3 /var/www/owncloud/lib/composer/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#4 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(479): Sabre\Event\EventEmitter->emit('method:DELETE', Array)
#5 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#6 /var/www/owncloud/apps/dav/appinfo/v1/webdav.php(63): Sabre\DAV\Server->exec()
#7 /var/www/owncloud/remote.php(165): require_once('/var/www/ownclo...')
#8 {main}","File":"/var/www/owncloud/apps/dav/lib/Connector/Sabre/File.php","Line":368,"User":"carlos"}"}
{"reqId":"zagWkq3oImubJatv094V","level":1,"time":"2018-02-10T21:28:00+01:00","remoteAddr":"10.1.10.85","user":"carlos","app":"admin_audit","method":"GET","url":"/remote.php/webdav/External-Storages/Ext-Dropbox/carlos.txt?downloadStartSecret=gl70873ylxf","message":"Read "/carlos/files/External-Storages/Ext-Dropbox/carlos.txt" by user <carlos>, displayName <Carlos Damken>, owner: carlos [CLIENT_IP: 10.1.10.85] [USER_AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0]"}
{"reqId":"ZyT1C3Xei2sWAz4y67X1","level":1,"time":"2018-02-10T21:28:11+01:00","remoteAddr":"10.1.10.85","user":"carlos","app":"admin_audit","method":"DELETE","url":"/remote.php/webdav/External-Storages/Ext-Dropbox/test1.txt","message":"Delete "/carlos/files/External-Storages/Ext-Dropbox/test1.txt" by user <carlos>, displayName <Carlos Damken>, owner: carlos [CLIENT_IP: 10.1.10.85] [USER_AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0]"}
{"reqId":"ZyT1C3Xei2sWAz4y67X1","level":2,"time":"2018-02-10T21:28:12+01:00","remoteAddr":"10.1.10.85","user":"carlos","app":"dav","method":"DELETE","url":"/remote.php/webdav/External-Storages/Ext-Dropbox/test1.txt","message":"Could not get node for path: "External-Storages/Ext-Dropbox/test1.txt" : {$message}"}
{"reqId":"EUCZIuUZxs432KlA2bWi","level":1,"time":"2018-02-10T21:28:19+01:00","remoteAddr":"10.1.10.85","user":"carlos","app":"admin_audit","method":"DELETE","url":"/remote.php/webdav/External-Storages/Ext-Dropbox/carlos.txt","message":"Delete "/carlos/files/External-Storages/Ext-Dropbox/carlos.txt" by user <carlos>, displayName <Carlos Damken>, owner: carlos [CLIENT_IP: 10.1.10.85] [USER_AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0]"}
{"reqId":"EUCZIuUZxs432KlA2bWi","level":0,"time":"2018-02-10T21:28:23+01:00","remoteAddr":"10.1.10.85","user":"carlos","app":"webdav","method":"DELETE","url":"/remote.php/webdav/External-Storages/Ext-Dropbox/carlos.txt","message":"Exception: {"Message":"HTTP/1.1 403 Forbidden","Exception":"Sabre\DAV\Exception\Forbidden","Code":0,"Trace":"
#0 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Tree.php(179): OCA\DAV\Connector\Sabre\File->delete()
#1 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/CorePlugin.php(287): Sabre\DAV\Tree->delete('External-Storag...')
#2 [internal function]: Sabre\DAV\CorePlugin->httpDelete(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#3 /var/www/owncloud/lib/composer/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#4 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(479): Sabre\Event\EventEmitter->emit('method:DELETE', Array)
#5 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#6 /var/www/owncloud/apps/dav/appinfo/v1/webdav.php(63): Sabre\DAV\Server->exec()
#7 /var/www/owncloud/remote.php(165): require_once('/var/www/ownclo...')
#8 {main}","File":"/var/www/owncloud/apps/dav/lib/Connector/Sabre/File.php","Line":368,"User":"carlos"}"}
{"reqId":"lMDmC3HHdpVWGAVsUJpo","level":1,"time":"2018-02-10T21:28:37+01:00","remoteAddr":"10.1.10.85","user":"carlos","app":"admin_audit","method":"DELETE","url":"/remote.php/webdav/External-Storages/Ext-Dropbox/carlos.txt","message":"Delete "/carlos/files/External-Storages/Ext-Dropbox/carlos.txt" by user <carlos>, displayName <Carlos Damken>, owner: carlos [CLIENT_IP: 10.1.10.85] [USER_AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0]"}
{"reqId":"lMDmC3HHdpVWGAVsUJpo","level":2,"time":"2018-02-10T21:28:39+01:00","remoteAddr":"10.1.10.85","user":"carlos","app":"dav","method":"DELETE","url":"/remote.php/webdav/External-Storages/Ext-Dropbox/carlos.txt","message":"Could not get node for path: "External-Storages/Ext-Dropbox/carlos.txt" : {$message}"}
```

**Comment by PVince81** [comment] 2018-02-12 08:41
@cdamken can you post the exact path is it exists in Dropbox and as it exists in ownCloud ?

Could be the uppercase/lowercase issue

cc @Hemant-Mann

**Comment by patrickjahns** [comment] 2018-02-12 12:12
@SergioBertolinSG 
Have you seen this issue during testing?

**Comment by SergioBertolinSG** [comment] 2018-02-12 13:24
I can reproduce it. I thought this was related with the slow performance during testing.

**Comment by Hemant-Mann** [comment] 2018-02-12 14:28
I am also able to reproduce it
I debugged this what i observed
- File was removed from Dropbox but error in ownCloud
- After file was removed there was a call to `file_exists` function which returned true (because of stat cache present with the adapter this is where the problem is)

I'll open a PR to address this and work on fixing the Unit Tests so as to prevent these kind of issues in future

**Comment by cdamken** [comment] 2018-02-12 16:49
> @cdamken can you post the exact path is it exists in Dropbox and as it exists in ownCloud ?
> 
> Could be the uppercase/lowercase issue

I have in: `/External-Storages/Ext-Dropbox`

I mounted in a sub-directory

**Comment by Hemant-Mann** [comment] 2018-04-24 09:36
This should be fixed by #32 

We should close this as well

**Comment by PVince81** [comment] 2018-04-24 09:39
thanks

**Closed by PVince81** 2018-04-24 09:39 UTC
Labels: bug, regression, sev2-high

**Comment by davitol** [comment] 2018-12-13 13:36
> I can reproduce it. I thought this was related with the slow performance during testing.

Reproduce too with the latest changes, using oC 10.0.10 and Tarball provide here: https://github.com/owncloud/files_external_dropbox/issues/10#issuecomment-442985547
