### ISSUE TITLE
Can not upload file into External Dropbox Storage

### ISSUE THREAD

**Issue by kiranadh1452** [owncloud/files_external_dropbox#138] opened 2022-07-13 10:23 UTC
### Steps to reproduce
1. Install External Storage - Dropbox
2. Create a dropbox app [here](https://www.dropbox.com/developers/apps)
3. Use the App Key and App Secret to create a external storage in owncloud.
4. Click on Grant Access and complete the steps until messge stating `External storage has been added successfully
` is observed.
5. Go to the newly mounted external storage.
6. Try uploading any file inside it.
7. Error message stating `Call to undefined function GuzzleHttp\Psr7\stream_for()` is observed

### Expected behaviour
- The file should have been uploaded successfully.

### Actual behaviour
- The file isn't uploaded and throws an error `Call to undefined function GuzzleHttp\Psr7\stream_for()`

### Server configuration
**Operating system**: ubuntu 20.04

**Web server:** apache2

**Database:** MySQL

**PHP version:** 7.4.3

**ownCloud version:** 10.11.0 prealpha (git)

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** github

**Comment by kiranadh1452** [comment] 2022-07-13 10:24
Based on: https://github.com/owncloud/files_external_dropbox/issues/137

**Comment by jnweiger** [comment] 2022-07-31 17:38
Same here.
Seen with files_external_dropbox=2.0.0-rc.1 running on core 10.11.0-alpha.2
![image](https://user-images.githubusercontent.com/1108546/182038602-2cfe7ebf-420c-4c21-928e-3770bad1d090.png)

The server log says:
```
{"reqId":"Yua8Gvd8j4mZljCp2j5GxQAAAAY","level":0,"time":"2022-07-31T17:30:03+00:00","remoteAddr":"89.204.135.225","user":"admin","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FDB","message":"token 7fb9ee4d4d7a9837b318b1f1e55075f26dd956bcc0c5009930175eafaaef5a65e59346b68dcce1d76725b102de8d4ff87ee226c0ebceadc4f08324bb7f3392d9 with token id 3 found, validating"}
{"reqId":"Yua8G5RSevGGHf@R8BeEjgAAAAA","level":0,"time":"2022-07-31T17:30:03+00:00","remoteAddr":"89.204.135.225","user":"admin","app":"OC\\User\\Session::validateToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/admin\/DB","message":"token 7fb9ee4d4d7a9837b318b1f1e55075f26dd956bcc0c5009930175eafaaef5a65e59346b68dcce1d76725b102de8d4ff87ee226c0ebceadc4f08324bb7f3392d9 with token id 3 found, validating"}
{"reqId":"Yua8JDBlJeDy@v-99aw@2QAAAAg","level":0,"time":"2022-07-31T17:30:12+00:00","remoteAddr":"89.204.135.225","user":"admin","app":"OC\\User\\Session::validateToken","method":"PUT","url":"\/remote.php\/dav\/files\/admin\/DB\/snapshot.jpg","message":"token 7fb9ee4d4d7a9837b318b1f1e55075f26dd956bcc0c5009930175eafaaef5a65e59346b68dcce1d76725b102de8d4ff87ee226c0ebceadc4f08324bb7f3392d9 with token id 3 found, validating"}
{"reqId":"Yua8JDBlJeDy@v-99aw@2QAAAAg","level":2,"time":"2022-07-31T17:30:15+00:00","remoteAddr":"89.204.135.225","user":"admin","app":"core","method":"PUT","url":"\/remote.php\/dav\/files\/admin\/DB\/snapshot.jpg","message":"ignoring lock release with type 1 for files\/ae3e667565874bf32675fb7468084f2a. Lock hasn't been acquired before"}
{"reqId":"Yua8JDBlJeDy@v-99aw@2QAAAAg","level":4,"time":"2022-07-31T17:30:15+00:00","remoteAddr":"89.204.135.225","user":"admin","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/files\/admin\/DB\/snapshot.jpg","message":"Exception: Call to undefined function GuzzleHttp\\Psr7\\stream_for(): {\"Exception\":\"Error\",\"Message\":\"Call to undefined function GuzzleHttp\\\\Psr7\\\\stream_for()\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external_dropbox\\\/vendor\\\/kunalvarma05\\\/dropbox-php-sdk\\\/src\\\/Dropbox\\\/DropboxFile.php(193): Kunnu\\\\Dropbox\\\\DropboxFile->open()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external_dropbox\\\/vendor\\\/kunalvarma05\\\/dropbox-php-sdk\\\/src\\\/Dropbox\\\/DropboxFile.php(168): Kunnu\\\\Dropbox\\\\DropboxFile->getStream()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external_dropbox\\\/vendor\\\/kunalvarma05\\\/dropbox-php-sdk\\\/src\\\/Dropbox\\\/Http\\\/RequestBodyStream.php(36): Kunnu\\\\Dropbox\\\\DropboxFile->getContents()\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external_dropbox\\\/vendor\\\/kunalvarma05\\\/dropbox-php-sdk\\\/src\\\/Dropbox\\\/DropboxClient.php(199): Kunnu\\\\Dropbox\\\\Http\\\\RequestBodyStream->getBody()\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external_dropbox\\\/vendor\\\/kunalvarma05\\\/dropbox-php-sdk\\\/src\\\/Dropbox\\\/DropboxClient.php(152): Kunnu\\\\Dropbox\\\\DropboxClient->prepareRequest()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external_dropbox\\\/vendor\\\/kunalvarma05\\\/dropbox-php-sdk\\\/src\\\/Dropbox\\\/Dropbox.php(273): Kunnu\\\\Dropbox\\\\DropboxClient->sendRequest()\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external_dropbox\\\/vendor\\\/kunalvarma05\\\/dropbox-php-sdk\\\/src\\\/Dropbox\\\/Dropbox.php(953): Kunnu\\\\Dropbox\\\\Dropbox->sendRequest()\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external_dropbox\\\/vendor\\\/kunalvarma05\\\/dropbox-php-sdk\\\/src\\\/Dropbox\\\/Dropbox.php(928): Kunnu\\\\Dropbox\\\\Dropbox->postToContent()\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external_dropbox\\\/vendor\\\/kunalvarma05\\\/dropbox-php-sdk\\\/src\\\/Dropbox\\\/Dropbox.php(878): Kunnu\\\\Dropbox\\\\Dropbox->startUploadSession()\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external_dropbox\\\/vendor\\\/hemant-mann\\\/flysystem-dropbox\\\/src\\\/Adapter.php(305): Kunnu\\\\Dropbox\\\\Dropbox->uploadChunked()\\n#10 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external_dropbox\\\/vendor\\\/hemant-mann\\\/flysystem-dropbox\\\/src\\\/Adapter.php(49): HemantMann\\\\Flysystem\\\\Dropbox\\\\Adapter->uploadChunked()\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external_dropbox\\\/vendor\\\/league\\\/flysystem\\\/src\\\/Filesystem.php(123): HemantMann\\\\Flysystem\\\\Dropbox\\\\Adapter->writeStream()\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Flysystem.php(213): League\\\\Flysystem\\\\Filesystem->putStream()\\n#13 [internal function]: OC\\\\Files\\\\Storage\\\\Flysystem->OC\\\\Files\\\\Storage\\\\{closure}(*** sensitive parameters replaced ***)\\n#14 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(119): call_user_func()\\n#15 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_close()\\n#16 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(96): fclose()\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Stream\\\/Checksum.php(151): Icewind\\\\Streams\\\\Wrapper->stream_close()\\n#18 [internal function]: OC\\\\Files\\\\Stream\\\\Checksum->stream_close()\\n#19 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(209): fclose()\\n#20 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(173): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put()\\n#21 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1098): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile()\\n#22 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(504): Sabre\\\\DAV\\\\Server->createFile()\\n#23 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpPut()\\n#24 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit()\\n#25 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n#26 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(349): Sabre\\\\DAV\\\\Server->start()\\n#27 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#28 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#29 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external_dropbox\\\/vendor\\\/kunalvarma05\\\/dropbox-php-sdk\\\/src\\\/Dropbox\\\/DropboxFile.php\",\"Line\":237}"}
{"reqId":"Yua8JDBlJeDy@v-99aw@2QAAAAg","level":1,"time":"2022-07-31T17:30:15+00:00","remoteAddr":"89.204.135.225","user":"admin","app":"core","method":"PUT","url":"\/remote.php\/dav\/files\/admin\/DB\/snapshot.jpg","message":"cleaning stray exclusive locks for files\/ae3e667565874bf32675fb7468084f2a"}
{"reqId":"Yua8KNM@iLcwMixrTVWZQAAAAAk","level":0,"time":"2022-07-31T17:30:16+00:00","remoteAddr":"89.204.135.225","user":"admin","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FDB","message":"token 7fb9ee4d4d7a9837b318b1f1e55075f26dd956bcc0c5009930175eafaaef5a65e59346b68dcce1d76725b102de8d4ff87ee226c0ebceadc4f08324bb7f3392d9 with token id 3 found, validating"}
{"reqId":"Yua8KNM@iLcwMixrTVWZQAAAAAk","level":0,"time":"2022-07-31T17:30:16+00:00","remoteAddr":"89.204.135.225","user":"admin","app":"OC\\Authentication\\Token\\DefaultTokenProvider::updateTokenActivity","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FDB","message":"updating activity of token 3 to 1659288616"}
{"reqId":"Yua8KNM@iLcwMixrTVWZQAAAAAk","level":0,"time":"2022-07-31T17:30:16+00:00","remoteAddr":"89.204.135.225","user":"admin","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FDB","message":"token 7fb9ee4d4d7a9837b318b1f1e55075f26dd956bcc0c5009930175eafaaef5a65e59346b68dcce1d76725b102de8d4ff87ee226c0ebceadc4f08324bb7f3392d9 with token id 3 found, validating"}
```

**Comment by jnweiger** [comment] 2022-07-31 17:45
The external drive remains empty, even after populating files on the dropbox server.
I assume, download is also affected, not only upload.

**Comment by jnweiger** [comment] 2022-08-01 00:36
## Workaround
Patch the kunalvarma05/dropbox-php-sdk contained in files_external_dropbox:

```
--- apps/files_external_dropbox/vendor/kunalvarma05/dropbox-php-sdk/src/Dropbox/DropboxFile.php.orig   2022-08-01 00:33:59.922899276 +0000
+++ apps/files_external_dropbox/vendor/kunalvarma05/dropbox-php-sdk/src/Dropbox/DropboxFile.php        2022-08-01 00:33:49.294407430 +0000
@@ -82,7 +82,8 @@
     public static function createByStream($fileName, $resource, $mode = self::MODE_READ)
     {
         // create a new stream and set it to the dropbox file
-        $stream = \GuzzleHttp\Psr7\stream_for($resource);
+        // $stream = \GuzzleHttp\Psr7\stream_for($resource);
+       $stream = \GuzzleHttp\Psr7\Utils::streamFor($resource);
         if (!$stream) {
             throw new DropboxClientException('Failed to create DropboxFile instance. Unable to open the given resource.');
         }
@@ -234,7 +235,8 @@
         }
 
         // Create a stream
-        $this->stream = \GuzzleHttp\Psr7\stream_for(fopen($this->path, $this->mode));
+        // $this->stream = \GuzzleHttp\Psr7\stream_for(fopen($this->path, $this->mode));
+        $this->stream = \GuzzleHttp\Psr7\Utils::streamFor(fopen($this->path, $this->mode));
 
         // Unable to create stream
         if (!$this->stream) {
```

**Comment by phil-davis** [comment] 2022-08-01 03:55
> can you make a sane fix from this?

Step 1: https://github.com/Hemant-Mann/flysystem-dropbox/pull/2

`Hemant-Mann/flysystem-dropbox` is restricting the upstream `kunalvarma05/dropbox-php-sdk` to release 0.2. If that can go up to 0.4 then we can see if the problem is already fixed, and if not, then contribute.

**Comment by phil-davis** [comment] 2022-08-01 06:43
https://github.com/kunalvarma05/dropbox-php-sdk/pull/195 already has the fix, but it is waiting for review, merge and release.

https://github.com/Hemant-Mann/flysystem-dropbox/pull/2 has been merged. That lets us pull in the latest `kunalvarma05/dropbox-php-sdk` - which I did in PR #142 - but that is just a demo, and we still need a new release of `kunalvarma05/dropbox-php-sdk`

**Comment by phil-davis** [comment] 2022-08-01 07:08
`kunalvarma05/dropbox-php-sdk` 0.4.1 has been released a few  minutes ago. I updated PR #142 

@jnweiger can you try the code from there easily?

If it improves things, then I will ask @Hemant-Mann to make an official release of `hemant-mann/flysystem-dropbox` which will allow all the upstream fixes.

**Comment by jnweiger** [comment] 2022-08-01 16:12
@phil-davis Re-Testing with 
```
  - Installing psr/http-client (1.0.1): Extracting archive
  - Installing guzzlehttp/guzzle (7.4.5): Extracting archive
  - Installing kunalvarma05/dropbox-php-sdk (v0.4.1): Extracting archive
  - Installing hemant-mann/flysystem-dropbox (v1.0.5): Extracting archive
```

**Comment by jnweiger** [comment] 2022-08-10 22:28
Closed fixed. Ready to release.

**Closed by jnweiger** 2022-08-10 22:28 UTC
